#!/bin/sh
# This is a generated file, do not edit!
# Ensure the script is executable: chmod +x gradlew
# Gradle Wrapper script to run Gradle tasks
# See: https://docs.gradle.org/current/userguide/gradle_wrapper.html
# For more information, visit https://github.com/gradle/gradle/blob/master/gradlew
# Generated by: Gradle Wrapper (version 7.4.2)
# Default JVM settings can be customized in gradle/wrapper/gradle-wrapper.properties
# Exit if any command fails
set -e
# Set up variables
GRADLE_HOME=$(dirname "$0")/gradle/wrapper
GRADLE_WRAPPER_JAR="$GRADLE_HOME/gradle-wrapper.jar"
# Check if Java is available
if command -v java >/dev/null 2>&1; then
    JAVA_CMD="java"
else
    echo "Java not found. Please install Java and try again."
    exit 1
fi
# Run Gradle
"$JAVA_CMD" -jar "$GRADLE_WRAPPER_JAR" "$@"
